baseURL = 'https://quickstart-hugo.pages.dev/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'exampleTheme'

pygmentsCodefences = true
pygmentsStyle = "rose-pine-moon"

guide = "https://zwbetz.com/syntax-highlighting-in-hugo-with-chroma"