baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'



[taxonomies]
  category = 'categories'
  tag = 'tags data backup'


[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Project"
    pre = "project"
    url = "/project/"
    weight = 3
  [[menu.main]]
    name = "About"
    pre = "about"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    pre = "contact"
    url = "/contact/"
    weight = 5
  [[menu.main]]
    name = "Resume"
    pre = "resume"
    url = "/resume/"
    weight = 6